### PR TITLE
Change content_blocks column in records table to longtext type

### PR DESCRIPTION
**Pull request by xtsidx**
Change content_blocks column in records table to longtext type

### CODE REVIEW

**Comment by jan-vince** [comment]
Hi @xtsidx,

I have no problem to change original TEXT type to somethig larger but I thing we should be ok with MEDIUMTEXT.

Or do you have any reason to use LONGTEXT?


Best regards,

Jan

**Comment by xtsidx** [comment]
Hi @jan-vince,

Sorry, I completely agree, LONGTEXT is overkill

MEDIUMTEXT Will be enough.

Thanks and nice day

**Review by jan-vince — CHANGES_REQUESTED** [review]
Ok, will you update this PR?

**Comment by xtsidx** [comment]
Ok, i did it

**Review by jan-vince — APPROVED** [review]
Thanks!

**Comment by jan-vince** [comment]
Hi @xtsidx just small note - I had to add another update to MEDIUMTEXT column as there is a bug in Laravel then TEXT column is not updated during migration. So the actual change is in version 3.8.3.


Best regards,

Jan

**Pull request merged**
